// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package repository

import (
	"errors"
	"fmt"
)

const (
	// StudyTypeБакалавриат is a StudyType of type Бакалавриат.
	StudyTypeБакалавриат StudyType = "Бакалавриат"
	// StudyTypeМагистратура is a StudyType of type Магистратура.
	StudyTypeМагистратура StudyType = "Магистратура"
	// StudyTypeАспирантура is a StudyType of type Аспирантура.
	StudyTypeАспирантура StudyType = "Аспирантура"
	// StudyTypeСпециалитет is a StudyType of type Специалитет.
	StudyTypeСпециалитет StudyType = "Специалитет"
)

var ErrInvalidStudyType = errors.New("not a valid StudyType")

// String implements the Stringer interface.
func (x StudyType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x StudyType) IsValid() bool {
	_, err := ParseStudyType(string(x))
	return err == nil
}

var _StudyTypeValue = map[string]StudyType{
	"Бакалавриат":  StudyTypeБакалавриат,
	"Магистратура": StudyTypeМагистратура,
	"Аспирантура":  StudyTypeАспирантура,
	"Специалитет":  StudyTypeСпециалитет,
}

// ParseStudyType attempts to convert a string to a StudyType.
func ParseStudyType(name string) (StudyType, error) {
	if x, ok := _StudyTypeValue[name]; ok {
		return x, nil
	}
	return StudyType(""), fmt.Errorf("%s is %w", name, ErrInvalidStudyType)
}
