// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package entities

import (
	"errors"
	"fmt"
)

const (
	// WeekTypeNumerator is a WeekType of type Numerator.
	WeekTypeNumerator WeekType = iota
	// WeekTypeDenominator is a WeekType of type Denominator.
	WeekTypeDenominator
)

var ErrInvalidWeekType = errors.New("not a valid WeekType")

const _WeekTypeName = "numeratordenominator"

var _WeekTypeMap = map[WeekType]string{
	WeekTypeNumerator:   _WeekTypeName[0:9],
	WeekTypeDenominator: _WeekTypeName[9:20],
}

// String implements the Stringer interface.
func (x WeekType) String() string {
	if str, ok := _WeekTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("WeekType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x WeekType) IsValid() bool {
	_, ok := _WeekTypeMap[x]
	return ok
}

var _WeekTypeValue = map[string]WeekType{
	_WeekTypeName[0:9]:  WeekTypeNumerator,
	_WeekTypeName[9:20]: WeekTypeDenominator,
}

// ParseWeekType attempts to convert a string to a WeekType.
func ParseWeekType(name string) (WeekType, error) {
	if x, ok := _WeekTypeValue[name]; ok {
		return x, nil
	}
	return WeekType(0), fmt.Errorf("%s is %w", name, ErrInvalidWeekType)
}
