// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package config

import (
	"errors"
	"fmt"
)

const (
	// RepositoryTypeFile is a RepositoryType of type file.
	RepositoryTypeFile RepositoryType = "file"
)

var ErrInvalidRepositoryType = errors.New("not a valid RepositoryType")

// String implements the Stringer interface.
func (x RepositoryType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x RepositoryType) IsValid() bool {
	_, err := ParseRepositoryType(string(x))
	return err == nil
}

var _RepositoryTypeValue = map[string]RepositoryType{
	"file": RepositoryTypeFile,
}

// ParseRepositoryType attempts to convert a string to a RepositoryType.
func ParseRepositoryType(name string) (RepositoryType, error) {
	if x, ok := _RepositoryTypeValue[name]; ok {
		return x, nil
	}
	return RepositoryType(""), fmt.Errorf("%s is %w", name, ErrInvalidRepositoryType)
}
